# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: CI
      working-directory: back-end
      run: |
          npm ci

    - name: Build
      working-directory: back-end
      run: |
          npm run build --if-present
          
    - name: Test
      working-directory: back-end
      run: |
          npm test
      env:
        CI: true
        FIREBASE_AUTH_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_AUTH_SERVICE_ACCOUNT }}
        FIREBASE_AUTH_API_KEY: ${{ secrets.FIREBASE_AUTH_API_KEY }}
        MONGODB_URI_LIVE: ${{ secrets.MONGODB_URI_LIVE }}